### ISSUE TITLE
code

### ISSUE THREAD

**Issue by yuqJin** [Armanasq/End-to-End-Deep-Learning-Framework-for-Real-Time-Inertial-Attitude-Estimation-using-6DoF-IMU#1]
Do you have plans to make the code public? The manuscript is rich in experiments, which is fascinating.

**Comment by Armanasq** [comment]
Thank you for your interest. Currently, the paper is under review, but once it is published, I will make the code public.

**Comment by Armanasq** [comment]
Hi,
The code is now online.
If you have any problems, please let know.
Best
